"use client";
import { useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { loadClients } from "@/lib/clientes";
import { addClientActivity } from "@/lib/client-activity";
import styles from "../NuevoNegocio.module.css";

type Line={id:string;number:string;action:"Portabilidad"|"Alta nueva";tariff:string;iccid:string;sim:"SIM"|"eSIM";donor:string;status:string;portDate:string};
const operators=["Vodafone","Orange","Movistar","DIGI","MásMóvil","Yoigo","Otro"];
const tariffs=["Ilimitada","100 GB","50 GB","25 GB","Solo voz","Otra"];
export default function TelefoniaPage(){
 const router=useRouter(); const search=useSearchParams(); const clients=useMemo(()=>loadClients().filter(c=>!c.deletedAt),[]);
 const [clientId,setClientId]=useState(search.get("cliente")||""); const [mode,setMode]=useState<"Comercial"|"BackOffice">("Comercial");
 const [saleType,setSaleType]=useState("Convergente"); const [operator,setOperator]=useState("Vodafone"); const [fiber,setFiber]=useState("1 Gb"); const [address,setAddress]=useState("");
 const [monthly,setMonthly]=useState(""); const [single,setSingle]=useState(""); const [vat,setVat]=useState("21"); const [notes,setNotes]=useState("");
 const [lines,setLines]=useState<Line[]>([{id:"l1",number:"",action:"Portabilidad",tariff:"Ilimitada",iccid:"",sim:"SIM",donor:"",status:"Pendiente BackOffice",portDate:""}]);
 const [activation,setActivation]=useState(""); const [reference,setReference]=useState(""); const client=clients.find(c=>c.id===clientId);
 const tax=1+Number(vat||0)/100; const monthlyTotal=Number(monthly||0)*tax; const singleTotal=Number(single||0)*tax;
 function addLine(){setLines(x=>[...x,{id:`l${Date.now()}`,number:"",action:"Portabilidad",tariff:"Ilimitada",iccid:"",sim:"SIM",donor:"",status:"Pendiente BackOffice",portDate:""}])}
 function update(id:string,key:keyof Line,value:string){setLines(x=>x.map(l=>l.id===id?{...l,[key]:value}:l))}
 function save(send=false){if(!clientId){alert("Selecciona un cliente.");return} const item={id:`tel-${Date.now()}`,service:"Telefonía",clientId,clientName:client?.name||"",saleType,operator,fiber,address,lines,monthly:Number(monthly||0),single:Number(single||0),vat:Number(vat||0),activation,reference,notes,status:send?"Pendiente BackOffice":"Borrador",createdAt:new Date().toISOString()}; const key="one_phone_opportunities_v1"; const prev=JSON.parse(localStorage.getItem(key)||"[]"); localStorage.setItem(key,JSON.stringify([item,...(Array.isArray(prev)?prev:[])])); addClientActivity({clientId,type:"Oportunidad",title:`Telefonía · ${saleType}`,detail:`${lines.length} línea(s) · ${send?"Pendiente BackOffice":"Borrador"}`,user:client?.commercial||"Usuario actual"}); alert(send?"Enviada a BackOffice. Ahora cambia a la pestaña BackOffice para probar la segunda fase.":"Borrador guardado.");}
 return <main className={styles.page}>
  <header className={styles.hero}><div><button type="button" onClick={()=>router.back()}>← Oportunidades</button><span>ONE · TELEFONÍA · PROTOTIPO</span><h1>Nueva oportunidad · Telefonía</h1><p>El comercial vende. BackOffice completa la tramitación.</p></div></header>
  <div className={styles.phoneRole}><button className={mode==="Comercial"?styles.phoneRoleActive:""} onClick={()=>setMode("Comercial")}>🟠 Comercial</button><button className={mode==="BackOffice"?styles.phoneRoleActive:""} onClick={()=>setMode("BackOffice")}>🔵 BackOffice</button></div>
  <div className={styles.workspace}><section className={styles.workArea}>
   <article className={styles.block}><div className={styles.blockHead}><span>01</span><div><h2>Cliente y venta</h2><p>Lo mínimo para construir la operación.</p></div></div><div className={styles.formGrid}>
    <label>Cliente *<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Seleccionar cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name} · {c.taxId}</option>)}</select></label>
    <label>Tipo de venta<select value={saleType} onChange={e=>setSaleType(e.target.value)}><option>Convergente</option><option>Solo fibra</option><option>Solo móvil</option><option>Fibra + móviles</option><option>Telefonía empresa</option></select></label>
    <label>Operador<select value={operator} onChange={e=>setOperator(e.target.value)}>{operators.map(x=><option key={x}>{x}</option>)}</select></label>
   </div></article>
   {saleType!=="Solo móvil"&&<article className={styles.block}><div className={styles.blockHead}><span>02</span><div><h2>Fibra</h2><p>Producto y domicilio de instalación.</p></div></div><div className={styles.formGrid}><label>Velocidad<select value={fiber} onChange={e=>setFiber(e.target.value)}><option>300 Mb</option><option>600 Mb</option><option>1 Gb</option><option>10 Gb</option></select></label><label className={styles.span2}>Domicilio instalación<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Solo si es distinto al domicilio del cliente"/></label></div></article>}
   {saleType!=="Solo fibra"&&<article className={styles.block}><div className={styles.blockHead}><span>03</span><div><h2>Líneas móviles</h2><p>{mode==="Comercial"?"Número, portabilidad y tarifa. Nada de ICCID todavía.":"Completa los datos técnicos sobre las líneas que ya vendió el comercial."}</p></div></div><div className={styles.phoneLines}>
    {lines.map((l,i)=><div className={styles.phoneLine} key={l.id}><b>Línea {i+1}</b><label>Número<input value={l.number} onChange={e=>update(l.id,"number",e.target.value)} placeholder="600 000 000"/></label><label>Operación<select value={l.action} onChange={e=>update(l.id,"action",e.target.value)}><option>Portabilidad</option><option>Alta nueva</option></select></label><label>Tarifa<select value={l.tariff} onChange={e=>update(l.id,"tariff",e.target.value)}>{tariffs.map(x=><option key={x}>{x}</option>)}</select></label>{mode==="BackOffice"&&<><label>ICCID<input value={l.iccid} onChange={e=>update(l.id,"iccid",e.target.value)} placeholder="8934..."/></label><label>SIM<select value={l.sim} onChange={e=>update(l.id,"sim",e.target.value)}><option>SIM</option><option>eSIM</option></select></label><label>Operador donante<input value={l.donor} onChange={e=>update(l.id,"donor",e.target.value)} placeholder="Operador actual"/></label><label>Fecha portabilidad<input type="date" value={l.portDate} onChange={e=>update(l.id,"portDate",e.target.value)}/></label><label>Estado<select value={l.status} onChange={e=>update(l.id,"status",e.target.value)}><option>Pendiente BackOffice</option><option>Solicitada</option><option>Portabilidad confirmada</option><option>Activada</option><option>Incidencia</option></select></label></>}</div>)}
    {mode==="Comercial"&&<button type="button" className={styles.phoneAdd} onClick={addLine}>＋ Añadir línea</button>}
   </div></article>}
   <article className={styles.block}><div className={styles.blockHead}><span>04</span><div><h2>Condiciones económicas</h2><p>Resumen de la venta; después lo conectaremos al catálogo real.</p></div></div><div className={styles.formGrid}><label>Cuota mensual €<input type="number" value={monthly} onChange={e=>setMonthly(e.target.value)}/></label><label>Pago único €<input type="number" value={single} onChange={e=>setSingle(e.target.value)}/></label><label>IVA<select value={vat} onChange={e=>setVat(e.target.value)}><option>21</option><option>10</option><option>0</option></select></label></div></article>
   {mode==="BackOffice"&&<article className={styles.block}><div className={styles.blockHead}><span>05</span><div><h2>Tramitación BackOffice</h2><p>Datos que no debe picar el comercial.</p></div></div><div className={styles.formGrid}><label>Referencia / nº pedido<input value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Fecha activación<input type="date" value={activation} onChange={e=>setActivation(e.target.value)}/></label><label className={styles.span2}>Incidencias / notas<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Solo si BackOffice necesita dejar constancia..."/></label></div></article>}
   <div className={styles.actions}><button className={styles.secondary} onClick={()=>router.back()}>Cancelar</button><button className={styles.secondary} onClick={()=>save(false)}>Guardar borrador</button>{mode==="Comercial"?<button className={styles.primary} onClick={()=>save(true)}>Enviar a BackOffice</button>:<button className={styles.primary} onClick={()=>save(false)}>Guardar tramitación</button>}</div>
  </section><aside className={styles.context}><article className={styles.contextCard}><span>RESUMEN</span><h3>{saleType}</h3><p>{operator} · {lines.length} línea(s)</p><div className={styles.phoneMoney}><small>Mensual IVA incl.</small><strong>{monthlyTotal.toFixed(2)} €</strong><small>Pago único IVA incl.</small><strong>{singleTotal.toFixed(2)} €</strong></div></article><article className={styles.advisor}><span>FILOSOFÍA ONE</span><h4>{mode==="Comercial"?"Vender, no tramitar":"Completar, no volver a picar"}</h4><p>{mode==="Comercial"?"Pide solo lo que el comercial conoce durante la venta. ICCID y datos técnicos quedan para BackOffice.":"BackOffice recibe la venta ya construida y añade únicamente los datos de alta, portabilidad y activación."}</p></article></aside></div>
 </main>
}
