"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Suspense, useEffect, useState } from "react";
import { supabaseBrowser } from "@/lib/supabase-browser";
import styles from "../Mail.module.css";
async function authToken(){const {data:{session}}=await supabaseBrowser.auth.getSession();if(!session?.access_token)throw new Error('Sesión no encontrada');return session.access_token}
export default function Compose(){return <Suspense fallback={<main className={styles.page}><div className={styles.panel}><div className={styles.loading}>Preparando correo…</div></div></main>}><ComposeContent /></Suspense>}
function ComposeContent(){const q=useSearchParams();const [to,setTo]=useState(q.get('to')||'');const [cc,setCc]=useState('');const [subject,setSubject]=useState(q.get('subject')||'');const [body,setBody]=useState(q.get('body')||'');const [account,setAccount]=useState<any>(null);const [sending,setSending]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const clientId=q.get('clientId')||'';const clientName=q.get('name')||'';
useEffect(()=>{(async()=>{try{const t=await authToken();const r=await fetch('/api/mail/accounts',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const j=await r.json();if(j.ok)setAccount(j.account)}catch{}})()},[]);
async function send(){setError('');setMessage('');if(!account){setError('Conecta primero tu cuenta de correo.');return}setSending(true);try{const t=await authToken();const r=await fetch('/api/mail/send',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({to,cc,subject,bodyText:body,clientId:clientId||null})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'No se pudo enviar');setMessage('Correo enviado desde ONE ✓');setSubject('');setBody('')}catch(e:any){setError(e?.message||'No se pudo enviar el correo')}finally{setSending(false)}}
return <main className={styles.page}><div className={styles.composer}><div className={styles.composerHead}><div><Link className={styles.back} href={clientId?`/clientes/${clientId}`:'/correo'}>← Volver</Link><span className={styles.eyebrow} style={{marginTop:18}}>ONE MAIL · REDACTAR</span><h1>{clientName?`Escribir a ${clientName}`:'Nuevo correo'}</h1></div><div className={styles.fromBox}>Enviar como<strong>{account?`${account.displayName} <${account.emailAddress}>`:'Cuenta sin conectar'}</strong></div></div>{error&&<div className={styles.error}>{error}</div>}{message&&<div className={styles.statusOk}>{message}</div>}<div className={styles.fields}><div className={styles.field}><label>Para</label><input value={to} onChange={e=>setTo(e.target.value)} placeholder="cliente@empresa.es"/></div><div className={styles.field}><label>CC</label><input value={cc} onChange={e=>setCc(e.target.value)} placeholder="Opcional"/></div><div className={styles.field}><label>Asunto</label><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Asunto"/></div></div><textarea className={styles.body} value={body} onChange={e=>setBody(e.target.value)} placeholder="Escribe tu mensaje…"/><div className={styles.composerFoot}><span className={styles.hint}>{clientId?'Este correo quedará vinculado al Cliente 360.':'El envío se registrará en ONE Mail.'}</span><div className={styles.actions}>{!account&&<Link className={styles.secondary} href="/correo/configuracion">Conectar cuenta</Link>}<button className={styles.primary} onClick={send} disabled={sending}>{sending?'Enviando…':'Enviar desde ONE →'}</button></div></div></div></main>}
