import { PageHead, Stat, Badge, EmptyLink } from "@/components/UI";
export default function Dashboard(){return <>
 <PageHead title="Buenos días, Jesús" subtitle="Este es el pulso comercial de AN24 hoy." action="Nueva oportunidad"/>
 <section className="hero"><div><Badge tone="light">RESUMEN DE JULIO</Badge><h2>Tu equipo mantiene un <b>78% de objetivo</b></h2><p>Hay 14 oportunidades listas para cerrar y 6 renovaciones que necesitan seguimiento.</p><button>Ver oportunidades prioritarias</button></div><div className="heroGauge"><span>78%</span><small>Objetivo mensual</small></div></section>
 <section className="stats"><Stat label="Clientes activos" value="1.284" delta="↑ 8,4% este mes" icon="◉"/><Stat label="Pipeline abierto" value="86.450 €" delta="14 cierres probables" icon="◇"/><Stat label="Ventas del mes" value="42.680 €" delta="↑ 12,1% vs. junio" icon="↗"/><Stat label="Tareas pendientes" value="23" delta="6 vencen hoy" icon="◷"/></section>
 <section className="grid2"><article className="panel"><div className="panelHead"><div><h3>Pipeline comercial</h3><p>Valor por fase</p></div><EmptyLink href="/oportunidades" label="Abrir pipeline"/></div><div className="bars">{[["Prospección",78,"28.400 €"],["Propuesta",61,"21.750 €"],["Negociación",46,"19.300 €"],["Cierre",35,"17.000 €"]].map(([n,w,v])=><div className="barRow" key={n as string}><span>{n}</span><div><i style={{width:`${w}%`}}/></div><b>{v}</b></div>)}</div></article>
 <article className="panel"><div className="panelHead"><div><h3>Agenda de hoy</h3><p>Lunes, 20 de julio</p></div><EmptyLink href="/agenda" label="Ver agenda"/></div><div className="agendaList">{[["09:30","Llamada renovación energía","Clínica Dental Sur"],["11:00","Demo TPV","Restaurante Albores"],["13:15","Seguimiento alarma","Estanco La Rotonda"],["17:00","Reunión comercial","Equipo AN24"]].map(x=><div className="agendaRow" key={x[0]}><time>{x[0]}</time><div><b>{x[1]}</b><span>{x[2]}</span></div></div>)}</div></article></section>
 <section className="grid3"><article className="panel span2"><div className="panelHead"><div><h3>Actividad reciente</h3><p>Últimos movimientos del equipo</p></div></div>{[["SR","Sara creó una oportunidad de Telefonía","Bar La Moderna · 2.450 €","Hace 12 min"],["JM","Jesús completó una tarea","Renovación de contrato energético","Hace 38 min"],["AC","Ana subió un documento","Contrato alarma · Cliente 1042","Hace 1 h"],["DR","David cambió una fase","TPV La Esquina → Negociación","Hace 2 h"]].map(x=><div className="activity" key={x[2]}><i>{x[0]}</i><div><b>{x[1]}</b><span>{x[2]}</span></div><time>{x[3]}</time></div>)}</article>
 <article className="panel"><h3>Servicios activos</h3>{[["Energía",412,"⚡"],["Telefonía",365,"☎"],["Alarmas",198,"◆"],["TPV",144,"▣"]].map(x=><div className="serviceLine" key={x[0] as string}><i>{x[2]}</i><span>{x[0]}</span><b>{x[1]}</b></div>)}</article></section>
 </>}
